services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=focus-tracker'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=boma'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres: